apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio
    spec:
      containers:
      - name: frontend
        image: gladysgodwin/portfolio_frontend:latest
        ports:
        - containerPort: 8090
      - name: backend
        image: gladysgodwin/portfolio_backend:latest
        ports:
        - containerPort: 9696
        env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres-url
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres_password
