apiVersion: v1
kind: Service
metadata:
  name: my-portfolio
  namespace: app
spec:
  selector:
    app: my-portfolio
  ports:
    - name: frontend
      port: 80
      protocol: TCP
      targetPort: 8090
    - name: frontend-https
      port: 443
      protocol: TCP
      targetPort: 3000
    - name: backend
      port: 9696
      protocol: TCP
      targetPort: 9696
  type: LoadBalancer
