version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "8090:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:gladys@db/postgres
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gladys
      POSTGRES_DB: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
