apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: my-website-portfolio
spec:
  ports:
  - port: 5432
  selector:
    app: my-website-portfolio
    tier: database
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: my-website-portfolio
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-website-portfolio
      tier: database
  template:
    metadata:
      labels:
        app: my-website-portfolio
        tier: database
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: gladys
        - name: POSTGRES_DB
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
