apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: my-website-portfolio
spec:
  type: LoadBalancer
  selector:
    app: my-website-portfolio
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 3000
